# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Ninechapterheadlines1
on:
  workflow_dispatch:
  schedule:
    - cron: '10 0,5,8,11,15,18,22,23 * * *'
  watch:
    types: started
  repository_dispatch:
    types: Ninechapterheadlines1
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【Ninechapterheadlines1】'
        run: |
          
          node Ninechapterheadlines1.js
        env:
        
          jzreadurl: ${{ secrets.jzreadurl }}
