# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青文章阅读翻倍-1-1
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * */7'
  watch:
    types: started
  repository_dispatch:
    types: Doubled-1-1
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【中青文章阅读翻倍-1-1】'
        run: |
          
          node Doubled-1-1.js
